namespace Chef.Shared.Resources
{
	//------------------------------------------------------------------------------
	// <auto-generated>
	//     This code was generated by a tool.
	//     Runtime Version:4.0.30319.42000
	//
	//     Changes to this file may cause incorrect behavior and will be lost if
	//     the code is regenerated.
	// </auto-generated>
	//------------------------------------------------------------------------------

	using System;


	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public partial class SharedResource
	{

		private static global::System.Resources.ResourceManager resourceMan;

		private static global::System.Globalization.CultureInfo resourceCulture;

		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal SharedResource()
		{
		}

		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Resources.ResourceManager ResourceManager
		{
			get
			{
				if (object.ReferenceEquals(resourceMan, null))
				{
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chef.Shared.Resources.SharedResource", typeof(SharedResource).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Globalization.CultureInfo Culture
		{
			get
			{
				return resourceCulture;
			}
			set
			{
				resourceCulture = value;
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Actions.
		/// </summary>
		public static string Actions
		{
			get
			{
				return ResourceManager.GetString("Actions", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Active.
		/// </summary>
		public static string Active
		{
			get
			{
				return ResourceManager.GetString("Active", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Add.
		/// </summary>
		public static string Add
		{
			get
			{
				return ResourceManager.GetString("Add", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Auditable fields.
		/// </summary>
		public static string AuditableFields
		{
			get
			{
				return ResourceManager.GetString("AuditableFields", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Cancel.
		/// </summary>
		public static string Cancel
		{
			get
			{
				return ResourceManager.GetString("Cancel", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Cancelled.
		/// </summary>
		public static string Cancelled
		{
			get
			{
				return ResourceManager.GetString("Cancelled", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Operation cancelled!.
		/// </summary>
		public static string CancelledOperation
		{
			get
			{
				return ResourceManager.GetString("CancelledOperation", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Close.
		/// </summary>
		public static string Close
		{
			get
			{
				return ResourceManager.GetString("Close", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The password and confirmation password do not match..
		/// </summary>
		public static string CompareConfirmationPassword
		{
			get
			{
				return ResourceManager.GetString("CompareConfirmationPassword", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Passwords must have uppercase and lowercase letters, numbers, and at least one non-alphanumeric character.
		/// </summary>
		public static string ComparePatternPassword
		{
			get
			{
				return ResourceManager.GetString("ComparePatternPassword", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Condition.
		/// </summary>
		public static string Condition
		{
			get
			{
				return ResourceManager.GetString("Condition", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Confirm.
		/// </summary>
		public static string Confirm
		{
			get
			{
				return ResourceManager.GetString("Confirm", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to You have successfully created the record {0}..
		/// </summary>
		public static string ConfirmationMessageCreate
		{
			get
			{
				return ResourceManager.GetString("ConfirmationMessageCreate", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to You have successfully deleted the record {0}..
		/// </summary>
		public static string ConfirmationMessageDelete
		{
			get
			{
				return ResourceManager.GetString("ConfirmationMessageDelete", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to You have successfully updated the record {0}..
		/// </summary>
		public static string ConfirmationMessageUpdate
		{
			get
			{
				return ResourceManager.GetString("ConfirmationMessageUpdate", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Confirmation of new password.
		/// </summary>
		public static string ConfirmationNewPassword
		{
			get
			{
				return ResourceManager.GetString("ConfirmationNewPassword", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Are you sure?.
		/// </summary>
		public static string ConfirmationQuestion
		{
			get
			{
				return ResourceManager.GetString("ConfirmationQuestion", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Confirm register.
		/// </summary>
		public static string ConfirmRegister
		{
			get
			{
				return ResourceManager.GetString("ConfirmRegister", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Create.
		/// </summary>
		public static string Create
		{
			get
			{
				return ResourceManager.GetString("Create", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Created.
		/// </summary>
		public static string Created
		{
			get
			{
				return ResourceManager.GetString("Created", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Created by.
		/// </summary>
		public static string CreatedBy
		{
			get
			{
				return ResourceManager.GetString("CreatedBy", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Date of creation.
		/// </summary>
		public static string CreationDate
		{
			get
			{
				return ResourceManager.GetString("CreationDate", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to mm/dd/yyyy.
		/// </summary>
		public static string CultureDateFormat
		{
			get
			{
				return ResourceManager.GetString("CultureDateFormat", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to MM/DD/YYYY h:mm:ss.
		/// </summary>
		public static string CultureDateTimeFormat
		{
			get
			{
				return ResourceManager.GetString("CultureDateTimeFormat", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to en-US.
		/// </summary>
		public static string CultureFormat
		{
			get
			{
				return ResourceManager.GetString("CultureFormat", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to /lib/DataTables-1.10.20/json/English.json.
		/// </summary>
		public static string DataTableLanguage
		{
			get
			{
				return ResourceManager.GetString("DataTableLanguage", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Delete.
		/// </summary>
		public static string Delete
		{
			get
			{
				return ResourceManager.GetString("Delete", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Deleted.
		/// </summary>
		public static string Deleted
		{
			get
			{
				return ResourceManager.GetString("Deleted", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to You will not be able to recover this record..
		/// </summary>
		public static string DeleteWarningMessage
		{
			get
			{
				return ResourceManager.GetString("DeleteWarningMessage", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The {0} field is not a valid e-mail address..
		/// </summary>
		public static string EmailInvalid
		{
			get
			{
				return ResourceManager.GetString("EmailInvalid", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to English.
		/// </summary>
		public static string English
		{
			get
			{
				return ResourceManager.GetString("English", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Field.
		/// </summary>
		public static string Field
		{
			get
			{
				return ResourceManager.GetString("Field", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to First login?.
		/// </summary>
		public static string FirstLogin
		{
			get
			{
				return ResourceManager.GetString("FirstLogin", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Forgot your password?.
		/// </summary>
		public static string ForgotPassword
		{
			get
			{
				return ResourceManager.GetString("ForgotPassword", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Help.
		/// </summary>
		public static string Help
		{
			get
			{
				return ResourceManager.GetString("Help", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Home.
		/// </summary>
		public static string Home
		{
			get
			{
				return ResourceManager.GetString("Home", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Id.
		/// </summary>
		public static string Id
		{
			get
			{
				return ResourceManager.GetString("Id", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Inactive.
		/// </summary>
		public static string Inactive
		{
			get
			{
				return ResourceManager.GetString("Inactive", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Invalid login attempt..
		/// </summary>
		public static string InvalidLoginAttempt
		{
			get
			{
				return ResourceManager.GetString("InvalidLoginAttempt", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Is active.
		/// </summary>
		public static string IsActive
		{
			get
			{
				return ResourceManager.GetString("IsActive", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Is deleted.
		/// </summary>
		public static string IsDeleted
		{
			get
			{
				return ResourceManager.GetString("IsDeleted", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to {0} field is required..
		/// </summary>
		public static string IsRequired
		{
			get
			{
				return ResourceManager.GetString("IsRequired", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The field is required..
		/// </summary>
		public static string IsRequiredSimple
		{
			get
			{
				return ResourceManager.GetString("IsRequiredSimple", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Login.
		/// </summary>
		public static string Login
		{
			get
			{
				return ResourceManager.GetString("Login", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Logout.
		/// </summary>
		public static string Logout
		{
			get
			{
				return ResourceManager.GetString("Logout", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The {0} field must be at least {1} characters long..
		/// </summary>
		public static string MinLength
		{
			get
			{
				return ResourceManager.GetString("MinLength", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The {0} field must be between {2} and {1} characters long..
		/// </summary>
		public static string MinMaxLength
		{
			get
			{
				return ResourceManager.GetString("MinMaxLength", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Modification date.
		/// </summary>
		public static string ModificationDate
		{
			get
			{
				return ResourceManager.GetString("ModificationDate", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Modified by.
		/// </summary>
		public static string ModifiedBy
		{
			get
			{
				return ResourceManager.GetString("ModifiedBy", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to My profile.
		/// </summary>
		public static string MyProfile
		{
			get
			{
				return ResourceManager.GetString("MyProfile", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to New tag.
		/// </summary>
		public static string NewTag
		{
			get
			{
				return ResourceManager.GetString("NewTag", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Next.
		/// </summary>
		public static string Next
		{
			get
			{
				return ResourceManager.GetString("Next", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No.
		/// </summary>
		public static string No
		{
			get
			{
				return ResourceManager.GetString("No", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No, cancel!.
		/// </summary>
		public static string NoCancel
		{
			get
			{
				return ResourceManager.GetString("NoCancel", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The password has been changed successfully. Please.
		/// </summary>
		public static string PasswordResetLink1
		{
			get
			{
				return ResourceManager.GetString("PasswordResetLink1", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to click here to log in.
		/// </summary>
		public static string PasswordResetLink2
		{
			get
			{
				return ResourceManager.GetString("PasswordResetLink2", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Choose a item.
		/// </summary>
		public static string PlaceholderSelect2
		{
			get
			{
				return ResourceManager.GetString("PlaceholderSelect2", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Previous.
		/// </summary>
		public static string Previous
		{
			get
			{
				return ResourceManager.GetString("Previous", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Detail view.
		/// </summary>
		public static string Read
		{
			get
			{
				return ResourceManager.GetString("Read", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Recover record.
		/// </summary>
		public static string RecoverDeleted
		{
			get
			{
				return ResourceManager.GetString("RecoverDeleted", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Password recovery.
		/// </summary>
		public static string RecoveryPassword
		{
			get
			{
				return ResourceManager.GetString("RecoveryPassword", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Restart.
		/// </summary>
		public static string Restart
		{
			get
			{
				return ResourceManager.GetString("Restart", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Return.
		/// </summary>
		public static string Return
		{
			get
			{
				return ResourceManager.GetString("Return", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Save.
		/// </summary>
		public static string Save
		{
			get
			{
				return ResourceManager.GetString("Save", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Search.
		/// </summary>
		public static string Search
		{
			get
			{
				return ResourceManager.GetString("Search", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Search panel.
		/// </summary>
		public static string SearchPanel
		{
			get
			{
				return ResourceManager.GetString("SearchPanel", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/i18n/en.js.
		/// </summary>
		public static string Select2Language
		{
			get
			{
				return ResourceManager.GetString("Select2Language", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Settings.
		/// </summary>
		public static string Settings
		{
			get
			{
				return ResourceManager.GetString("Settings", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Show deleted records.
		/// </summary>
		public static string ShowDeletedRecords
		{
			get
			{
				return ResourceManager.GetString("ShowDeletedRecords", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Show inactive records.
		/// </summary>
		public static string ShowInactiveRecords
		{
			get
			{
				return ResourceManager.GetString("ShowInactiveRecords", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Spanish.
		/// </summary>
		public static string Spanish
		{
			get
			{
				return ResourceManager.GetString("Spanish", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Status.
		/// </summary>
		public static string Status
		{
			get
			{
				return ResourceManager.GetString("Status", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Submit.
		/// </summary>
		public static string Submit
		{
			get
			{
				return ResourceManager.GetString("Submit", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Update.
		/// </summary>
		public static string Update
		{
			get
			{
				return ResourceManager.GetString("Update", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Updated.
		/// </summary>
		public static string Updated
		{
			get
			{
				return ResourceManager.GetString("Updated", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Update date.
		/// </summary>
		public static string UpdateDate
		{
			get
			{
				return ResourceManager.GetString("UpdateDate", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Updated by.
		/// </summary>
		public static string UpdatedBy
		{
			get
			{
				return ResourceManager.GetString("UpdatedBy", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to User logged in..
		/// </summary>
		public static string UserLoggedIn
		{
			get
			{
				return ResourceManager.GetString("UserLoggedIn", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Enter a valid 4 digit Year..
		/// </summary>
		public static string ValidYear
		{
			get
			{
				return ResourceManager.GetString("ValidYear", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Value.
		/// </summary>
		public static string Value
		{
			get
			{
				return ResourceManager.GetString("Value", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Welcome.
		/// </summary>
		public static string Welcome
		{
			get
			{
				return ResourceManager.GetString("Welcome", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Yes.
		/// </summary>
		public static string Yes
		{
			get
			{
				return ResourceManager.GetString("Yes", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Yes, I&apos;m sure!.
		/// </summary>
		public static string YesSure
		{
			get
			{
				return ResourceManager.GetString("YesSure", resourceCulture);
			}
		}
	}
}
